const productlist =[{
  id:1,
  name:"dell",
  quantity:10,
  imgURL:"assets/1.png",
  category:1,
  price:2525,
  CreatedADd : "Mar 2 2022",
  description:"Paragraphs are the building blocks of papers. Many students define paragraphs in t erms of length: a paragraph is a group oft orasingle sentence thatformsanit”(Lunsford andConnors 116).Length and appearance do not determine whetherasection in a paper is a paragraph. For instance, in some styles of writing, particularly journalistic styles,e long. Ultimately",
},
{
  id:2,
  name:"hd",
  quantity:7,
  imgURL:"assets/2.jpg",
  category:2,
  price:2552,
  CreatedADd : "Feb 8 2022",
  description:"Paragraphs are the building blocks of papers. Many students define paragraphs in t erms of length: a paragraph is a group oft orasingle sentence thatformsanit”(Lunsford andConnors 116).Length and appearance do not determine whetherasection in a paper is a paragraph. For instance, in some styles of writing, particularly journalistic styles,e long. Ultimately",
},
{
  id:3,
  name:"acer",
  quantity:6,
  imgURL:"assets/3.jpeg",
  category:2,
  price:4252,
  CreatedADd : "jan 9 2021",
  description:"Paragraphs are the building blocks of papers. Many students define paragraphs in t erms of length: a paragraph is a group oft orasingle sentence thatformsanit”(Lunsford andConnors 116).Length and appearance do not determine whetherasection in a paper is a paragraph. For instance, in some styles of writing, particularly journalistic styles,e long. Ultimately",
},
{
  id:4,
  name:"lenovo",
  quantity:15,
  imgURL:"assets/4.jpg",
  category:3,
  price:4182,
  CreatedADd : "july 3 2022",
  description:"Paragraphs are the building blocks of papers. Many students define paragraphs in t erms of length: a paragraph is a group oft orasingle sentence thatformsanit”(Lunsford andConnors 116).Length and appearance do not determine whetherasection in a paper is a paragraph. For instance, in some styles of writing, particularly journalistic styles,e long. Ultimately",
},
{
  id:5,
  name:"toshiba",
  quantity:7,
  imgURL:"assets/5.jpeg",
  category:3,
  price:1404,
  CreatedADd : "OCT 4 2023",
  description:"Paragraphs are the building blocks of papers. Many students define paragraphs in t erms of length: a paragraph is a group oft orasingle sentence thatformsanit”(Lunsford andConnors 116).Length and appearance do not determine whetherasection in a paper is a paragraph. For instance, in some styles of writing, particularly journalistic styles,e long. Ultimately",
},
{
  id:6,
  name:"appel",
  quantity:11,
  imgURL:"assets/6.jpg",
  category:4,
  price:3621,
  CreatedADd : "NOV 1 2019",
  description:"Paragraphs are the building blocks of papers. Many students define paragraphs in t erms of length: a paragraph is a group oft orasingle sentence thatformsanit”(Lunsford andConnors 116).Length and appearance do not determine whetherasection in a paper is a paragraph. For instance, in some styles of writing, particularly journalistic styles,e long. Ultimately",
},
{
  id:7,
  name:"Kako",
  quantity:11,
  imgURL:"assets/1.png",
  category:3,
  price:1120,
  CreatedADd : "JAN 8 2021",
  description:"Paragraphs are the building blocks of papers. Many students define paragraphs in t erms of length: a paragraph is a group oft orasingle sentence thatformsanit”(Lunsford andConnors 116).Length and appearance do not determine whetherasection in a paper is a paragraph. For instance, in some styles of writing, particularly journalistic styles,e long. Ultimately",
},
{
  id:8,
  name:"Opoo",
  quantity:9,
  imgURL:"assets/3.jpeg",
  category:4,
  price:4112,
  CreatedADd : "OCT 14 2018",
  description:"Paragraphs are the building blocks of papers. Many students define paragraphs in t erms of length: a paragraph is a group oft orasingle sentence thatformsanit”(Lunsford andConnors 116).Length and appearance do not determine whetherasection in a paper is a paragraph. For instance, in some styles of writing, particularly journalistic styles,e long. Ultimately",
},
{
  id:9,
  name:"Samsung",
  quantity:21,
  imgURL:"assets/2.jpg",
  category:2,
  price:6421,
  CreatedADd : "JULY 16 2017",
  description:"Paragraphs are the building blocks of papers. Many students define paragraphs in t erms of length: a paragraph is a group oft orasingle sentence thatformsanit”(Lunsford andConnors 116).Length and appearance do not determine whetherasection in a paper is a paragraph. For instance, in some styles of writing, particularly journalistic styles,e long. Ultimately",
},
{
  id:10,
  name:"LG",
  quantity:45,
  imgURL:"assets/4.jpg",
  category:3,
  price:2525,
  CreatedADd : "Feb 17 2019",
  description:"Paragraphs are the building blocks of papers. Many students define paragraphs in t erms of length: a paragraph is a group oft orasingle sentence thatformsanit”(Lunsford andConnors 116).Length and appearance do not determine whetherasection in a paper is a paragraph. For instance, in some styles of writing, particularly journalistic styles,e long. Ultimately",
},
]
export default productlist
